export const images = [
  {
    src: "/art/linkedinbridgecropped.png",
    alt: "linkedin bridge",
    title: "linkedin bridge",
    date: "02/12/24",
    media: "procreate",
  },
  {
    src: "/art/blue.jpeg",
    alt: "butterflies",
    title: "blue butterflies",
    date: "07/10/2021",
    media: "colour pencils",
  },
  {
    src: "/art/portugal.jpg",
    alt: "europe architecture",
    title: "architecture in europe",
    date: "03/20/2024",
    media: "winsor newton watercolour",
  },
  {
    src: "/art/watercolour.JPG",
    alt: "purple watercolour",
    title: "day in the life",
    date: "03/20/2024",
    media: "winsor newton watercolour",
  },
  {
    src: "/art/red.jpeg",
    alt: "red",
    title: "filtered red",
    date: "05/16/2021",
    media: "pencil crayons",
  },
  {
    src: "/art/gold.jpeg",
    alt: "gold",
    title: "gold",
    date: "07/10/2021",
    media: "colour pencils",
  },
  {
    src: "/art/makicrop.jpg",
    alt: "maki",
    title: "maki from jjk",
    date: "07/10/2022",
    media: "krita digital art",
  },
  {
    src: "/art/uncle.jpg",
    alt: "hey",
    title: "uncle",
    date: "07/10/2021",
    media: "krita digital art",
  },
  { src: "/art/blue.jpeg", alt: "hey", title: "blue" },
  {
    src: "/art/csmbg1.jpg",
    alt: "hey",
    title: "chainsawman",
    date: "03/20/2022",
    media: "krita digital art",
  },
  {
    src: "/art/gold.jpeg",
    alt: "hey",
    title: "gold",
    date: "07/10/2021",
    media: "colour pencils",
  },
];
